name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # 1. Check out the repo
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the Gatsby site
      - name: Build Gatsby
        run: npm run build

      # 5. Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. Deploy to S3
      # IAM User has the least privileges possible to deploy to this S3 bucket & invalidate CF cache
      - name: Deploy to S3
        run: |
          aws s3 sync public/ s3://${{ secrets.S3_BUCKET }}/ \
            --region ${{ secrets.AWS_REGION }} \
            --delete \
            --cache-control=no-cache,no-store,must-revalidate \
            --acl private
          
      # 7. Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
